spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - file:/Users/d1sslow/IdeaProjects/SmartHome-tech/infra/config-server/src/main/resources/config/telemetry/
            - file:/Users/d1sslow/IdeaProjects/SmartHome-tech/infra/config-server/src/main/resources/config/commerce/

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true