spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_cart
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false

server:
  port: 0
  servlet:
    context-path: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  server:
    port: 8082
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.yandex.practicum: DEBUG