spring:
  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-group
    auto-offset-reset: earliest
    enable-auto-commit: false
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: INFO