spring:
  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-group
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: INFO
    com.netflix.eureka: DEBUG